### ISSUE TITLE
[Bug]: Gateway disconnect causing a Python seg fault error that causes Home Assistant runtime to fail and Home Assistant crashes and reboots

### ISSUE THREAD

**Issue by cypht** [maginawin/ha-dali-center#63]
### Version

0.11.0

### Home Assistant Version

2025.12.1

### Home Assistant Installation Type

Home Assistant Operating System (HAOS)

### Gateway Software Version

3.65

### Gateway Firmware Version

1.47

### What happened?

# Python Segfault (Signal 11) When MQTT Connection Resets

## Summary
The DALI Center integration causes Home Assistant to crash with a Python segmentation fault (Signal 11) when MQTT connections to DALI gateways are reset or experience network errors. This results in complete system crashes requiring automatic restart.

## Environment
- **Home Assistant Version:** 2025.12.1
- **DALI Center Version:** 0.11.0
- **Operating System:** Home Assistant OS (HassOS)
- **Installation Type:** Home Assistant OS on QEMU/KVM VM
- **Python Version:** 3.13 (from logs)
- **System Memory:** 16GB RAM

## Issue Description
Home Assistant experiences complete crashes (Python segfault) when DALI gateways disconnect or MQTT socket connections are reset. The crash occurs during normal runtime (after 2-18 hours of uptime) and is triggered by network socket errors.

### Crash Pattern
1. DALI gateways experience network connectivity issues
2. MQTT client receives socket error: `[Errno 104] Connection reset by peer`
3. Python process terminates with Signal 11 (SEGV)
4. Home Assistant automatically restarts
5. Database shows unclean shutdown

## Steps to Reproduce
1. Install DALI Center integration with multiple DALI gateways over MQTT
2. Configure gateways at different IP addresses
3. Run Home Assistant normally for several hours
4. Trigger network disruption or MQTT connection reset to any gateway
5. Observe Python segmentation fault crash

## Expected Behavior
When MQTT connections fail or reset:
- Integration should handle socket errors gracefully
- MQTT client should attempt reconnection
- Home Assistant should log errors but continue running
- No Python segfault should occur

## Actual Behavior
When MQTT connections reset:
- Python process terminates abnormally with Signal 11 (SEGV)
- Home Assistant crashes completely
- Database shutdown is unclean (data corruption risk)
- System must restart automatically

### MQTT Socket Errors Before Crash
2025-12-08 10:04:54.488 ERROR (paho-mqtt-client-ha_dali_center_26250205591A) [paho.mqtt.client] failed to receive on socket: [Errno 104] Connection reset by peer 2025-12-08 10:04:54.488 WARNING (paho-mqtt-client-ha_dali_center_26250205591A) [PySrDaliGateway.gateway] Gateway 26250205591A: Unexpected MQTT disconnection (172.16.1.21:1883) - Reason code: Unspecified error 2025-12-08 10:04:57.880 ERROR (paho-mqtt-client-ha_dali_center_F6250205622F) [paho.mqtt.client] failed to receive on socket: [Errno 104] Connection reset by peer 2025-12-08 10:04:57.880 WARNING (paho-mqtt-client-ha_dali_center_F6250205622F) [PySrDaliGateway.gateway] Gateway F6250205622F: Unexpected MQTT disconnection (172.16.1.22:1883) - Reason code: Unspecified error 2025-12-08 10:04:58.904 ERROR (paho-mqtt-client-ha_dali_center_362502056106) [paho.mqtt.client] failed to receive on socket: [Errno 104] Connection reset by peer 2025-12-08 10:04:58.904 WARNING (paho-mqtt-client-ha_dali_center_362502056106) [PySrDaliGateway.gateway] Gateway 362502056106: Unexpected MQTT disconnection (172.16.1.25:1883) - Reason code: Unspecified error

### Segmentation Fault (Host Logs)
2025-12-06 13:05:02.083 systemd-coredump[5832]: Process 5740 (python3) of user 0 terminated abnormally with signal 11/SEGV, processing... 2025-12-06 13:05:02.132 systemd-coredump[5833]: Process 5740 (python3) of user 0 terminated abnormally without generating a coredump.

### Home Assistant Container Exit
[04:20:10] INFO: Home Assistant Core finish process exit code 256 [04:20:10] INFO: Home Assistant Core finish process received signal 11

### Database Corruption Evidence
2025-12-08 09:50:15.596 WARNING (Recorder) [homeassistant.components.recorder.util] The system could not validate that the sqlite3 database at //config/home-assistant_v2.db was shutdown cleanly 2025-12-08 09:50:15.654 WARNING (Recorder) [homeassistant.components.recorder.util] Ended unfinished session (id=317 from 2025-12-07 15:38:29.065455)

## Crash Timeline Analysis

| Session | Start Time | Crash Time | Uptime | Trigger |
|---------|-----------|-----------|--------|---------|
| 314 | 2025-12-07 11:57:30 | 2025-12-07 19:40:10 | 2h 13m | MQTT errors → Segfault |
| 317 | 2025-12-07 15:38:29 | 2025-12-08 09:50:10 | 18h | MQTT errors → Segfault |

Pattern: System runs normally for hours, then MQTT connection issues trigger immediate Python segfault.

## Potential Root Cause
The segfault appears to occur when the DALI Center MQTT client (paho-mqtt) encounters socket errors. Possible issues:
1. **Improper exception handling** in MQTT disconnect callback
2. **Memory corruption** when handling socket errors
3. **C extension or native library** in PySrDaliGateway causing segfault
4. **Thread safety issue** in MQTT client error handling
5. **Missing null pointer checks** when connection resets

## Request
Could you please investigate:
1. Exception handling around MQTT socket operations in PySrDaliGateway
2. Thread safety in MQTT disconnect/error callbacks
3. Any C extensions that might cause segfaults on network errors
4. Adding graceful reconnection logic when socket errors occur

## Additional Logs Available
I can provide:
- Full Home Assistant logs
- Host system logs showing Python segfaults
- Core dumps (if available)
- DALI gateway MQTT broker logs
- Network packet captures

[home-assistant_2025-12-08T05-52-27.929Z.log](https://github.com/user-attachments/files/24025259/home-assistant_2025-12-08T05-52-27.929Z.log)

Please let me know what additional information would be helpful for debugging.

## Impact
This bug makes Home Assistant unstable and causes:
- Complete system crashes every 2-18 hours
- Database corruption from unclean shutdowns
- Loss of automation reliability
- Potential data loss

Thank you for maintaining this integration!

### Steps to Reproduce

1. Install DALI Center integration with multiple DALI gateways over MQTT
2. Configure gateways at different IP addresses
3. Run Home Assistant normally for several hours
4. Trigger network disruption or MQTT connection reset to any gateway
5. Observe Python segmentation fault crash

### Logs

```shell

```

**Comment by cypht** [comment]
Doesnt look like it is causing the runtime to fail anymore. But I do see these logs, please verify if that is intended. This is while 3 gateways are left offline. 

`2025-12-09 16:27:57.792 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 2625020558C6 at 172.16.1.23:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:27:57.792 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 2625020558C6: Network error connecting to gateway 2625020558C6: [Errno 113] Host is unreachable
2025-12-09 16:28:00.864 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 22250205551A at 172.16.1.24:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:28:00.864 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 22250205551A: Network error connecting to gateway 22250205551A: [Errno 113] Host is unreachable
2025-12-09 16:28:03.936 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 0225020273AC at 172.16.1.26:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:28:03.936 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 0225020273AC: Network error connecting to gateway 0225020273AC: [Errno 113] Host is unreachable
2025-12-09 16:28:10.975 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 2625020558C6 at 172.16.1.23:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:28:10.976 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 2625020558C6: Network error connecting to gateway 2625020558C6: [Errno 113] Host is unreachable
2025-12-09 16:28:14.432 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 22250205551A at 172.16.1.24:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:28:14.432 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 22250205551A: Network error connecting to gateway 22250205551A: [Errno 113] Host is unreachable
2025-12-09 16:28:17.504 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 0225020273AC at 172.16.1.26:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:28:17.504 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 0225020273AC: Network error connecting to gateway 0225020273AC: [Errno 113] Host is unreachable
2025-12-09 16:28:34.272 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 2625020558C6 at 172.16.1.23:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:28:34.272 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 2625020558C6: Network error connecting to gateway 2625020558C6: [Errno 113] Host is unreachable
2025-12-09 16:28:37.664 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 22250205551A at 172.16.1.24:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:28:37.664 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 22250205551A: Network error connecting to gateway 22250205551A: [Errno 113] Host is unreachable
2025-12-09 16:28:40.736 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 0225020273AC at 172.16.1.26:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:28:40.736 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 0225020273AC: Network error connecting to gateway 0225020273AC: [Errno 113] Host is unreachable
2025-12-09 16:29:17.472 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 2625020558C6 at 172.16.1.23:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:29:17.472 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 2625020558C6: Network error connecting to gateway 2625020558C6: [Errno 113] Host is unreachable
2025-12-09 16:29:21.248 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 22250205551A at 172.16.1.24:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:29:21.248 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 22250205551A: Network error connecting to gateway 22250205551A: [Errno 113] Host is unreachable
2025-12-09 16:29:24.320 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 0225020273AC at 172.16.1.26:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:29:24.320 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 0225020273AC: Network error connecting to gateway 0225020273AC: [Errno 113] Host is unreachable
2025-12-09 16:30:40.928 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 2625020558C6 at 172.16.1.23:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:30:40.928 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 2625020558C6: Network error connecting to gateway 2625020558C6: [Errno 113] Host is unreachable
2025-12-09 16:30:44.832 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 22250205551A at 172.16.1.24:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:30:44.832 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 22250205551A: Network error connecting to gateway 22250205551A: [Errno 113] Host is unreachable
2025-12-09 16:30:47.904 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 0225020273AC at 172.16.1.26:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:30:47.904 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 0225020273AC: Network error connecting to gateway 0225020273AC: [Errno 113] Host is unreachable
2025-12-09 16:32:04.128 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 2625020558C6 at 172.16.1.23:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:32:04.128 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 2625020558C6: Network error connecting to gateway 2625020558C6: [Errno 113] Host is unreachable
2025-12-09 16:32:08.224 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 22250205551A at 172.16.1.24:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:32:08.224 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 22250205551A: Network error connecting to gateway 22250205551A: [Errno 113] Host is unreachable
2025-12-09 16:32:11.296 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 0225020273AC at 172.16.1.26:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:32:11.296 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 0225020273AC: Network error connecting to gateway 0225020273AC: [Errno 113] Host is unreachable
2025-12-09 16:33:27.264 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 2625020558C6 at 172.16.1.23:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:33:27.264 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 2625020558C6: Network error connecting to gateway 2625020558C6: [Errno 113] Host is unreachable
2025-12-09 16:33:31.552 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 22250205551A at 172.16.1.24:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:33:31.552 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 22250205551A: Network error connecting to gateway 22250205551A: [Errno 113] Host is unreachable
2025-12-09 16:33:34.624 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 0225020273AC at 172.16.1.26:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:33:34.624 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 0225020273AC: Network error connecting to gateway 0225020273AC: [Errno 113] Host is unreachable
2025-12-09 16:34:50.720 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 2625020558C6 at 172.16.1.23:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:34:50.720 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 2625020558C6: Network error connecting to gateway 2625020558C6: [Errno 113] Host is unreachable
2025-12-09 16:34:55.072 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 22250205551A at 172.16.1.24:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible
2025-12-09 16:34:55.072 WARNING (MainThread) [custom_components.dali_center] Error connecting to gateway 22250205551A: Network error connecting to gateway 22250205551A: [Errno 113] Host is unreachable
2025-12-09 16:38:52.546 ERROR (paho-mqtt-client-ha_dali_center_0225020273AC) [paho.mqtt.client] failed to receive on socket: [Errno 104] Connection reset by peer
2025-12-09 16:38:52.547 WARNING (paho-mqtt-client-ha_dali_center_0225020273AC) [PySrDaliGateway.gateway] Gateway 0225020273AC: Unexpected MQTT disconnection (172.16.1.26:1883) - Reason code: Unspecified error
2025-12-09 16:38:53.485 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 111] Connection refused
2025-12-09 16:38:55.396 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 111] Connection refused
2025-12-09 16:38:59.699 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 111] Connection refused
2025-12-09 16:39:07.519 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 111] Connection refused
2025-12-09 16:39:22.780 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 111] Connection refused
2025-12-09 16:39:53.515 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 111] Connection refused
2025-12-09 16:40:51.466 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 111] Connection refused
2025-12-09 16:42:05.262 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: 
2025-12-09 16:43:05.580 ERROR (MainThread) [homeassistant.components.analytics] Error sending analytics to https://analytics-api.home-assistant.io/v1: ClientConnectorDNSError(ConnectionKey(host='analytics-api.home-assistant.io', port=443, is_ssl=True, ssl=True, proxy=None, proxy_auth=None, proxy_headers_hash=None), OSError(None, 'Timeout while contacting DNS servers'))
2025-12-09 16:52:05.942 WARNING (paho-mqtt-client-ha_dali_center_0225020273AC) [PySrDaliGateway.gateway] Gateway 0225020273AC: Unexpected MQTT disconnection (172.16.1.26:1883) - Reason code: Keep alive timeout
2025-12-09 16:52:09.312 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 16:52:14.368 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 16:52:21.408 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 16:52:29.024 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 16:52:47.456 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 16:53:20.992 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 16:54:19.360 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 16:55:27.071 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 16:56:34.208 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 16:57:43.136 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 16:58:50.144 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 16:59:48.320 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 17:00:47.648 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 17:01:50.944 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 17:02:43.239 ERROR (MainThread) [PySrDaliGateway.discovery] Socket error in receiver loop - this may prevent discovery: [Errno 9] Bad file descriptor
2025-12-09 17:02:59.552 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 17:03:57.984 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 17:05:01.408 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 17:06:05.280 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable
2025-12-09 17:07:12.608 WARNING (MainThread) [PySrDaliGateway.gateway] Gateway 0225020273AC: Reconnection attempt failed: [Errno 113] Host is unreachable`



Specifically these two lines ->

`2025-12-09 17:02:43.239 ERROR (MainThread) [PySrDaliGateway.discovery] Socket error in receiver loop - this may prevent discovery: [Errno 9] Bad file descriptor`

`2025-12-09 16:34:50.720 ERROR (MainThread) [PySrDaliGateway.gateway] Network error connecting to gateway 2625020558C6 at 172.16.1.23:1883: [Errno 113] Host is unreachable - check if gateway is powered on and accessible`

**Comment by cypht** [comment]
## Signal 11 (Segmentation Fault) during Home Assistant startup - Race condition in event.py with `call_soon_threadsafe()`

### Description

Home Assistant crashes with **Signal 11 (SEGV) segmentation fault** during startup when DALI Center is loaded alongside other custom integrations. The crash occurs due to a **race condition** in `event.py` where `call_soon_threadsafe()` is called from the MQTT background thread before the asyncio event loop is fully initialized.

### Environment

- **Home Assistant Version**: 2025.12.1 (Core)
- **DALI Center Version**: 0.11.1
- **Python Version**: 3.13
- **Installation Type**: Home Assistant OS
- **DALI Hardware**: Multiple DALI gateways with MQTT connections

### Symptoms

1. **Immediate crash on startup** with exit code 256 and Signal 11
2. **Crash log evidence**:
ERROR (paho-mqtt-client) failed to receive on socket: [Errno 104] Connection reset by peer systemd-coredump: Process python3 terminated abnormally with signal 11/SEGV
3. **Workaround**: Disabling DALI Center allows HA to start; re-enabling it one-by-one after startup works fine
4. **Pattern**: Only crashes when **all custom integrations load concurrently** during initial system boot/reboot

### Steps to Reproduce

1. Install DALI Center and 2-3 other resource-intensive custom integrations (e.g., Bermuda BLE, Frigate, Atomberg, etc.)
2. Configure multiple DALI gateways with MQTT connections
3. Perform a **full system reboot** (not just HA restart)
4. Observe Signal 11 crash during startup
5. Disable DALI Center → System starts successfully
6. Re-enable DALI Center after startup → System continues working fine

### Root Cause Analysis

The issue appears to be in [`custom_components/dali_center/event.py` at line 124](https://github.com/maginawin/ha-dali-center/blob/main/custom_components/dali_center/event.py#L124):

```python
def _handle_device_update(self, status: PanelStatus) -> None:
 """Handle device status update from MQTT background thread."""
 
 @callback
 def _fire_event() -> None:
     event_data: dict[str, str | int] = {
         "entity_id": self.entity_id,
         "event_type": event_name,
     }
     self.hass.bus.async_fire(f"{DOMAIN}_event", event_data)
     self.schedule_update_ha_state()

 # Called from paho-mqtt background thread during startup
 self.hass.loop.call_soon_threadsafe(_fire_event)  # <- SEGFAULT HERE
```

### Why This Crashes

1. During Home Assistant startup, the asyncio event loop may not be fully initialized
2. DALI Center's MQTT client (paho-mqtt) connects in a background thread
3. MQTT receives device status updates immediately after connection
4. _handle_device_update() is called from the MQTT background thread (not the main event loop thread)
5. call_soon_threadsafe() is invoked before the event loop is ready to accept callbacks
6. This causes a segmentation fault in Python's threading/asyncio internals

#### Why It Works When Enabled Individually: 
When DALI Center is the only integration loading (or loaded after others), the event loop has sufficient time to fully initialize, avoiding the race condition.

### Impact
1. Severity: Critical - Causes system-wide crashes preventing Home Assistant from starting
2. Frequency: 100% reproducible on systems with multiple custom integrations
3. Workaround: Disable/re-enable DALI Center after startup (not a sustainable solution)

### Additional Context
This appears to be a thread-safety issue where background thread callbacks are scheduled to the event loop during the critical startup phase. The crash only manifests when multiple integrations compete for resources during concurrent initialization. The segmentation fault occurs in Python's core threading/asyncio layer, suggesting that call_soon_threadsafe() needs additional safety guards when called from background threads during startup.

### Expected Behavior
DALI Center should handle startup race conditions gracefully and not crash Home Assistant when multiple integrations initialize concurrently.

**Comment by niracler** [comment]
> ### Root Cause Analysis
> The issue appears to be in [`custom_components/dali_center/event.py` at line 124](https://github.com/maginawin/ha-dali-center/blob/main/custom_components/dali_center/event.py#L124):
> 
> def _handle_device_update(self, status: PanelStatus) -> None:
>  """Handle device status update from MQTT background thread."""
>  
>  @callback
>  def _fire_event() -> None:
>      event_data: dict[str, str | int] = {
>          "entity_id": self.entity_id,
>          "event_type": event_name,
>      }
>      self.hass.bus.async_fire(f"{DOMAIN}_event", event_data)
>      self.schedule_update_ha_state()


@cypht  This has been fixed in **v0.11.2** via PR #65.

## Root Cause

You correctly identified the issue! The `call_soon_threadsafe()` in `event.py` was redundant because the underlying PySrDaliGateway library already dispatches callbacks to the event loop via `call_soon_threadsafe()`. The double dispatch caused race conditions during startup.

## Fix

Removed the redundant `call_soon_threadsafe()` wrapper. The callback handlers now use the `@callback` decorator and execute directly since they're already dispatched to the correct thread by the library.

**Comment by niracler** [comment]
@cypht  I've released v0.11.3 with a potential fix for this issue. 

What changed: Added a semaphore to serialize gateway initialization. Previously, when multiple gateways were configured, they all tried to connect simultaneously during HA startup, which could overload the event loop. Now only 2 gateways initialize concurrently. I don't have a multi-gateway setup to reproduce this, so I'd appreciate it if you could test and let me know:

- Update to v0.11.3 via HACS or manually
- Restart Home Assistant
- Report back whether Signal 11 crashes still occur

**Comment by cypht** [comment]
Still getting crashes. Although very few now. Potential Issue identified.




## Signal 11 Crashes Persist After Thread-Safety Fix: Missing Rate Limiting for `call_soon_threadsafe()`

---

### Environment

- **Home Assistant Core Version**: Latest  
- **PySrDaliGateway Version**: Latest (with thread-safety fix applied)  
- **Python Version**: 3.13  
- **Number of Gateways**: 6 (≈300 total devices)  
- **Database**: MariaDB  
- **Comparison System**: Zigbee2MQTT with 700+ devices (no crashes observed)

---

### Summary

Home Assistant continues to crash with **Signal 11 (SEGV – segmentation fault)** even after implementing thread-safety fixes in **PySrDaliGateway** (`_dispatch_callback()` and `_set_event_threadsafe()`).

The crashes now occur specifically when one or more gateways send **bursts of MQTT messages**, overwhelming the asyncio event loop with **hundreds of simultaneous `call_soon_threadsafe()` calls** coming from multiple paho-mqtt threads.

The current thread-safety implementation is **correct**, but **insufficient under high message volume** because there is **no rate limiting, batching, or throttling** for inbound callbacks.

---

### Thread-Safety Fix Status ✅

The recently implemented thread-safety mechanisms are correct and working as intended.

**File**: `PySrDaliGateway/gateway.py`

```python
def _dispatch_callback(self, callback: Callable[..., Any], *args: Any) -> None:
    """Dispatch a callback in a thread-safe manner."""
    if self._loop is not None and self._loop.is_running():
        self._loop.call_soon_threadsafe(callback, *args)  # ✅ Thread-safe
    else:
        callback(*args)


def _notify_listeners(self, event_type, dev_id, data) -> None:
    """Notify all registered listeners."""
    for listener in self._device_listeners.get(event_type, {}).get(dev_id, []):
        self._dispatch_callback(listener, data)  # ✅ Uses thread-safe dispatch
````

✔ This ensures callbacks are marshalled safely to the event loop.
❌ However, **it does not protect the event loop from overload** when message volume is high.

---

### The Remaining Problem: No Rate Limiting ❌

#### Crash Evidence from Logs

**Crash at 20:04:53 (Dec 12, 2025)**

Gateway **`2625020558C6`** sent a burst of **20+ `onlineStatus` messages in ~20 seconds**:

```text
[20:04:33.619] Gateway 2625020558C6: onlineStatus address 0 → False
[20:04:34.219] Gateway 2625020558C6: onlineStatus address 3 → False
[20:04:34.819] Gateway 2625020558C6: onlineStatus address 10 → False
[20:04:35.419] Gateway 2625020558C6: onlineStatus address 14 → False
[20:04:36.019] Gateway 2625020558C6: onlineStatus address 17 → False
[20:04:36.619] Gateway 2625020558C6: onlineStatus address 22 → False
[20:04:37.219] Gateway 2625020558C6: onlineStatus address 23 → False
[20:04:37.819] Gateway 2625020558C6: onlineStatus address 45 → False
[20:04:38.420] Gateway 2625020558C6: onlineStatus address 13 → False
[20:04:39.019] Gateway 2625020558C6: onlineStatus address 28 → False
... (10+ more messages)
[20:04:53.680] Gateway 2625020558C6: onlineStatus address 48 → True
```

Immediately after:

```text
[14:35:10] Home Assistant Core finish process exit code 256
[14:35:10] Home Assistant Core finish process received signal 11
```

This resulted in **3 consecutive crashes** in rapid succession:

* 20:04:53
* +4 seconds
* +12 seconds

---

### What Happens During Message Bursts

With **6 gateways × ~50 devices × multiple listeners per device**, the following occurs:

#### MQTT Thread (Gateway 2625020558C6)

```text
Message #1 → _on_message()
  → _process_online_status()
  → _notify_listeners()
    → _dispatch_callback()
      → call_soon_threadsafe(callback_1, data)
      → call_soon_threadsafe(callback_2, data)

Message #2 → _on_message()
  → _process_online_status()
  → _notify_listeners()
    → call_soon_threadsafe(callback_1, data)
    → call_soon_threadsafe(callback_2, data)

... (20+ messages)
```

#### Parallel MQTT Threads

```text
Gateway 26250205591A → call_soon_threadsafe() ...
Gateway 362502056106 → call_soon_threadsafe() ...
... (4 more gateways, each with its own paho-mqtt thread)
```

**Result**:
Hundreds of `call_soon_threadsafe()` calls per second from **6 concurrent MQTT threads**.

---

### Why High-Volume `call_soon_threadsafe()` Causes Signal 11

Based on CPython internals:

* **Internal Queue**: `call_soon_threadsafe()` pushes callbacks into a shared queue protected by locks.
* **Lock Contention**: Multiple paho-mqtt threads compete for the same event-loop lock.
* **Memory Pressure**: Each call allocates callback handles.
* **Known CPython Weakness**: Extreme `call_soon_threadsafe()` volume under heavy contention can lead to instability.

**Result**:
Memory corruption / race conditions → **Signal 11 (SIGSEGV)**.

---

### Code Analysis: Missing Rate Limiting

#### Existing Outbound Batching (Good)

The library already batches **outbound commands**:

```python
self._window_ms = 100  # Batch outbound commands
self._pending_requests: Dict[str, Dict[str, Dict[str, Any]]] = {}
self._batch_timer: Dict[str, asyncio.TimerHandle] = {}

def add_request(self, cmd, dev_type, channel, address, data):
    self._pending_requests[cmd][device_key] = data

def _flush_batch(self, cmd):
    self._mqtt_client.publish(self._pub_topic, json.dumps(command))
```

✔ Outbound traffic is batched and throttled.

#### Inbound Callbacks (Problem)

```python
def _process_online_status(self, payload: Dict[str, Any]) -> None:
    for data in data_list:
        dev_id = gen_device_unique_id(...)
        available: bool = data.get("status", False)
        self._notify_listeners(CallbackEventType.ONLINE_STATUS, dev_id, available)
        # ❌ Immediate dispatch
        # ❌ No queueing
        # ❌ No throttling
        # ❌ No debouncing
```

Each inbound MQTT message **immediately dispatches callbacks** to all listeners.

---

### What’s Needed

Inbound callback handling needs the same protection as outbound commands:

* **Queue inbound callbacks** instead of dispatching immediately
* **Process callbacks in batches** on the event loop
* **Debounce rapid state changes** (e.g., online/offline flapping)
* **Rate limit callback dispatch** to protect `call_soon_threadsafe()`

---

### Why Zigbee2MQTT Works with 700+ Devices

Zigbee2MQTT does not crash because it:

* Uses Home Assistant’s **built-in MQTT integration**
* Applies **rate limiting and debouncing**
* Uses **queue-based processing with backpressure**
* Runs callbacks **directly in the event loop thread**
* Avoids massive `call_soon_threadsafe()` bursts

---

### Specific Gateway Issue: `2625020558C6`

This gateway consistently appears in crash reports:

* Sends **large message bursts** (20+ messages in seconds)
* Shows **device flapping** (rapid online/offline changes)
* Fails to fully initialize at startup
* Involved in **~75% of observed crashes**

Possible causes:

* Gateway firmware bug
* Network instability
* Physical/electrical issues

**Regardless**, the library should handle such message bursts gracefully and never crash the host application.

---

### Reproduction Steps

1. Configure **6 DALI gateways** with ~50 devices each (≈300 total)
2. Enable debug logging for `PySrDaliGateway`
3. Wait for one or more gateways to send burst `onlineStatus` messages
4. Observe **Signal 11 crash** when multiple gateways send messages concurrently

---

### Expected Behavior

The library should handle **high-frequency MQTT message bursts** safely, regardless of:

* Message volume
* Number of gateways
* Device flapping or reconnect storms

Worst case should be **delayed processing**, not a segmentation fault.

---

### Actual Behavior

* Python crashes with **Signal 11 (SIGSEGV)**
* Home Assistant Core exits with code `256`
* Supervisor restarts Home Assistant
* Service disruption occurs

---

### Impact

* **Frequency**: Multiple crashes per hour during normal operation
* **Scope**: Systems with multiple gateways and high device counts (300+)
* **Severity**: **Critical** – full Home Assistant restart
* **Trigger**: Any MQTT message burst from multiple gateways

#### Scale Dependency

* **1 gateway (~50 devices)**: Rare crashes
* **6 gateways (~300 devices)**: Frequent crashes

---

This issue persists despite correct thread-safety fixes and appears to require **rate limiting, batching, or queue-based processing for inbound MQTT callbacks** to prevent event-loop overload and segmentation faults.

```
```

**Comment by niracler** [comment]
@cypht Hi, we've released v0.11.5 with PySrDaliGateway 0.19.3, which includes callback batching for better performance and client ID timestamps to prevent duplicate reconnections. Please update and let us know if the issue persists.

**Comment by cypht** [comment]
This previous bug is fixed.

Note: I’m seeing a separate issue unrelated to the segfault in this ticket:
**Brightness slider/state desync only for DALI groups** (individual lights OK). I’ve opened a new issue for it here: #73
